### ISSUE TITLE
How to add restrictions to find method

### ISSUE THREAD

**Issue by pinicius** [supaldubey/storm#2]
Hi,
first of all, congratulations for this great library.
I have read the "documentation" and I haven't got any information about this.

Can you show me an example using a "WHERE" restriction?

Thanks

**Comment by supaldubey** [comment]
Glad you liked it. You can see some examples for using WHERE / Restrictions below in the Test class

https://github.com/supaldubey/storm/blob/master/src/test/java/in/cubestack/android/lib/storm/criteria/MultiCriteriaTests.java

`
restrictions = StormRestrictions.restrictionsFor(TestEntity.class);
Restriction idRes = restrictions.equals("id", 7);
Restriction name = restrictions.likeIgnoreCase("name", "SUPAL DUBEY");
Restriction combo = restrictions.and(idRes, name);

// You may choose to use any of the restrictions here, either Combo or single 
responseList = stormService.find(TestEntity.class, combo);
`

I will also update the documentation to reflect this. Thanks

**Comment by pinicius** [comment]
Thanks!
One question: I have 3 tables. Table 1 has relation "hasMany" with Table 2 and, Table 2 has a relation "hasMany" with Table 3. I reflect these facts with storm and, in fact, the data is saved correctly into database (I check it). I've seen, in the log, that when I call storm.findAll(Table1.class) only makes one LEFT OUTER JOIN. How can I get all the related information with only one call with storm?

Thanks again Bruce ;)

**Comment by supaldubey** [comment]
Unfortunately there is no direct way to achieve this. This was a very conscious design decision taken not to implement m*n fetch for more than one level. 

If table1 was mapped with "hasMany" with Table2 and Table3 there would have been 2 LEFT OUTER JOINS. Usually from experience there are not many cases where you might require 2 levels of relation data to be fetched at once on Android we did not implement it. 

Also, it is really difficult to Optimize mapping time and performance in such cases, also the size of fetch is significant on Cursor (N rows in table1 * M rows of Table2 * Z rows from Table3). What we do in our apps if usually trigger another find call to storm with selected or only required Table3 entities

**Comment by pinicius** [comment]
Alright, I understand your decision. However, the relations between tables (T1 and T2; T2 and T3) are 1*N --> Experiments have many groups. Group belongs only to one Experiment. Groups have many Subjects. Subject belongs to one Group. It's not so weird this case, don't you think ;))?
In any case, thank you!
