### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by firebiird** [supaldubey/storm#3]
Hello, 

The migrations on tables doesn't seem to work that well, If it fails to migrate it will still bump the version. If you skip a version also it doesn't pick up changes in the past version.

Is there a way if I detect a table which hasn't been migrated properly to re do the migration script?  

Lee.

**Comment by supaldubey** [comment]
Ideally Storm is designed to handle those scenarios, by checking the current database version with the version in which table was created: 
`//If table version is current DB version or it was added in earlier version.
				if ( (information.getTableVersion() == metaData.getVersion()) || (oldVersion < information.getTableVersion()) ) {`

Or Altered: 
`/// If column was added in this version or version later than last DB version
            if ( (newVersion <= columnMetaData.getAddedVersion() ) || (oldVersion <= columnMetaData.getAddedVersion()))  {`


Technically, if the versioning is correct; that is `added ` attribute in table, and column annotations are in sync with @Database annotation, everything should be smooth. One of our [App](https://play.google.com/store/apps/details?id=in.cubestack.coins): had the same scenario and is working quite well. 

If it still occurs, I would consider it a bug and would fix it for the next version (or patch fix). Can you provide more details?

**Comment by firebiird** [comment]
I think I know why this wasn't working as expected for me. The table generation script seems to go through the table array passed into the Database class in the order the classes were specified. This means when I specified one of my child tables before the table it was referenced in I got a table not found exception. which then throws the whole migration process off but stopping there and still bumping the version up to the next version. 

Ideally if the table does not exist it should create the table (unless failing) if it does fail the migration process it shouldn't bump the version of the DB up because it makes it a nightmare to issue a retrospective fix. 

Lee.

**Comment by supaldubey** [comment]
OK great! 
Knowing this makes the solution clear at least. 

For your comment, the issue is while opening the SQLite DB, we need to pass the version and the version is bumped already by the time onUpgrade callback is received. 

I will do a fix for your issue and perform another release, ideally sorting the tables and reordering seems to be the fix for this. 

Thanks
