### ISSUE TITLE
Changing list of tables

### ISSUE THREAD

**Issue by errorman-awful** [supaldubey/storm#5]
If we declare some tables,launch the app,then change list of tables,and launch again,the lib will NOT create new table

**Comment by supaldubey** [comment]
For new tables to reflect sqlite db needs to be notified of newer version.

To do this simply update version number on @Database annotation and add new entity in tables class.

@Database(name="MY_DB", tables = {Entity.class, AnotherEntity.class}, version = 2)
class Database {}


On table annotation you would need to add addedVersion =2.

With these two steps you should be able to see new tables on relaunch or upgrade

**Comment by errorman-awful** [comment]
Thanks,sorry for fake reports,that's my fault

ср, 8 мая 2019 г., 5:56 Supal Dubey <notifications@github.com>:

**Comment by supaldubey** [comment]
No issues, happy to help
