### ISSUE TITLE
Queries on onUpgrade and close DB

### ISSUE THREAD

**Issue by rishabhk669** [supaldubey/storm#7]
Hi,

I have a working application but now I want to change its database with ORM and I found your library may help me out. I haven't started yet to use it because before I start I want to get below doubts clear. I don't want to mess-up the code so, I thought to get clarification before start-on.

1. How to handle "onUpgrade" event
2. How to close database after completing operation or if it is auto-closeable

Please answer above queries.

Regards,
Rishabh

**Comment by supaldubey** [comment]
Thanks for planning to use Storm Rishabh

`How to handle "onUpgrade" event` - Library would handle itself, you just need to define your version in `@Database` annotation. It would also create tables / add columns as required.

 `How to close database after completing operation or if it is auto-closeable` - You don't need to worry about it, storm would manage connections for you.

**Comment by rishabhk669** [comment]
Hi,

So, will @Database handle change in column without deleting data? In case if I change a filed name then how it will be able to maintain data. For example, if Table "Student" has a filed "name" and later I want to change it to "firstName" and "lastName" then if I can handle "onUpadte" then I will split "name" via space and put it in respective field. 
How to handle it via Strom?

**Comment by supaldubey** [comment]
Yes, storm will handle DB column additions for you, it does not delete any data or drop columns or tables. These operations will be handled by Storm, no code required. 

For performing any additional post processing, you may choose to provide `DatabaseUpdatesHandler` implementation on `@Database`. 

This class gives you callback function, here you may choose to perform any operation you feel that would make sense, in above example splitting columns.  

```
@Override
public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
		
}
```

**Comment by rishabhk669** [comment]
This sounds great. Thanks a lot for clarifying the query and for such a nice library.
